apply from: "$rootProject.projectDir/common/library-module.gradle"
apply from: "$rootProject.projectDir/common/dependencies.gradle"
android {
    namespace 'com.android.pokedex.core.core_data.api'
}

dependencies {
    implementation project(':core:core_model')
    implementation project(':core:core_api:di')
}