apply from: "$rootProject.projectDir/common/library-module.gradle"
apply from: "$rootProject.projectDir/common/dependencies.gradle"

android {
    namespace 'com.android.pokedex.feature.pokemomn_details'
}

dependencies {
    implementation project(":core:core_resources:provider:api")
    implementation project(":core:core_resources")
    implementation project(":core:core_domain:model")
    implementation project(":core:core_common:helpers")
    implementation project(":core:core_ui")
    implementation project(":navigation:api")
    implementation project(":core:core_domain:session")
    implementation project(":core:core_domain:interactor:api")
}