apply from: "$rootProject.projectDir/common/library-module.gradle"
apply from: "$rootProject.projectDir/common/dependencies.gradle"
android {
    namespace 'com.android.pokedex.core.core_ui'
}

dependencies {
    implementation project(':core:core_resources')
    implementation project(':core:core_domain:model')
}