apply from: "$rootProject.projectDir/common/library-module.gradle"
apply from: "$rootProject.projectDir/common/dependencies.gradle"
android {
    namespace 'com.android.pokedex.core.core_domain.controller.impl'
}

dependencies {
    implementation project(':core:core_domain:controller:api')
    implementation project(':core:core_resources:provider:api')
    implementation project(':core:core_domain:model')
    implementation project(':core:core_resources')

}